/*
 * Paul A. Chernick Software
 *
 * Dialog class template for dialogs that are not generated by QT Creator or QT Designer. 
 * This template avoids the UI class created by QT Creator and QT Designer.
 *
 * This is the minimum needed to create a new dialog class.
 * 
 * Globally replace PACSWBASEDIALOG_H_ with the proper include guard macro.
 * Globally relpace PACSWBaseDialog with the proper name for the class.
 * 
 */
#include "pacswBaseDialog.h"
#include <QVariant>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFormLayout>
#include "createNamedQTWidget.h"

PACSWBaseDialog::PACSWBaseDialog(QWidget *parent) :
    QDialog(parent)
{
    setObjectName(QString::fromUtf8("PACSWBaseDialog"));

    setUpDialogUI();

/*
 * QMetaObject::connectSlotsByName() does not connect Dialog Button Box buttons
 * or checkboxes. This makes it necessary to connect the buttons and checkboxes
 * explicitly.
 */
    connectDialogButtons();

    QMetaObject::connectSlotsByName(this);
}

void PACSWBaseDialog::setUpDialogUI()
{
    QVBoxLayout* PACSWBaseDialogLayout = new QVBoxLayout;
    PACSWBaseDialogLayout->setObjectName("PACSWBaseDialogLayout");

    QDialogButtonBox* pacswDialogButtonBox = setUpButtonBox();
    PACSWBaseDialogLayout->addWidget(pacswDialogButtonBox, 0, Qt::AlignHCenter);

    PACSWBaseDialogLayout->setSpacing(groupBoxSpacing);

    setLayout(PACSWBaseDialogLayout);

    QString dialogTitle = windowTitle();
    dialogTitle += "TITLE";

    setWindowTitle(dialogTitle);
}


QDialogButtonBox *PACSWBaseDialog::setUpButtonBox()
{
    QDialogButtonBox *buttonBox = new QDialogButtonBox(this);

    buttonBox->setObjectName(QString::fromUtf8("PACSWDialogButtonBox"));
    buttonBox->setGeometry(QRect(0, 500, 341, 32));
    buttonBox->setOrientation(Qt::Horizontal);
    buttonBox->setStandardButtons(QDialogButtonBox::Cancel|QDialogButtonBox::Ok);

    return buttonBox;
}


void  PACSWBaseDialog::connectDialogButtons()
{
}


QFormLayout* PACSWBaseDialog::createNamedFormLayoutWithPolicy(const char *formName)
{
    QFormLayout* newFormLayout = createNamedQTWidget<QFormLayout>(formName);
    newFormLayout->setFieldGrowthPolicy(QFormLayout::ExpandingFieldsGrow);

    return newFormLayout;
}

/*
 * Slots for the widgets.
 */
void PACSWBaseDialog::onAccept()
{
}


