/*
 * Paul A. Chernick Software
 *
 * Dialog class template for dialogs that are not generated by QT Creator or QT Designer. 
 * This template avoids the UI class created by QT Creator and QT Designer.
 *
 * This is the minimum needed to create a new dialog class.
 * 
 * Globally replace PACSWBASEDIALOG_H_ with the proper include guard macro.
 * Globally relpace PACSWBaseDialog with the proper name for the class.
 * 
 */
#ifndef PACSWBASEDIALOG_H_
#define PACSWBASEDIALOG_H_

#include <QVariant>
#include <QDialog>
#include <QDialogButtonBox>
#include <QFormLayout>
#include "createNamedQTWidget.h"

class PACSWBaseDialog : public QDialog
{
    Q_OBJECT

public:
    explicit PACSWBaseDialog(QWidget* parent = nullptr);
    ~PACSWBaseDialog() = default;

public slots:

signals:
    void validatePACSWBaseDialog();

private slots:
    void onAccept();

private:
    void setUpDialogUI();
    QDialogButtonBox* setUpButtonBox();
    void connectDialogButtons();
    QFormLayout *createNamedFormLayoutWithPolicy(const char *formName);

/*
 * Add pointers to QWidgets as necessary.
 */

    const int groupBoxSpacing = 60;
/*
 * Add other constants as necessary.
 */
};

#endif  // PACSWBASEDIALOG_H_
